import type { InferGetStaticPropsType } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import jsonata from 'jsonata';

import { getStoryblokStories } from 'moncel-one-sdk/cdn';
import { StoryblokLayoutHeaderLink as HeaderLink } from 'moncel-one-sdk/cdn/types';

import StepsSection from 'components/landing/steps';
import PricingSection from 'components/landing/pricing';
import FAQSection from 'components/landing/faq';
import CTASection from 'components/landing/cta';
import Footer from 'components/landing/footer';

import icxstyles from '../styles/icx.module.scss'

const Home = (props: InferGetStaticPropsType<typeof getStaticProps>) => {
  const headerLinks = props.layout?.content?.header?.[0].navigation;
  const faqs = jsonata('content.body[component="section_faqs"]').evaluate(props.home)
  const footer = props.layout?.content?.footer?.[0]
  return (
    <div>
      <Head>
        <title>Food Handler Certificate Course Online | 100% Online</title>
        <meta name="description" content="Generated by create next app" />
        {/* bootstrap responsive viewport meta tag */}
        {/* <meta name="viewport" content="width=device-width, initial-scale=1" />  */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={icxstyles.page}>
        
        {/* header */}
        <div className={icxstyles['header-bg']} />
        <div className={icxstyles.header}>
          <div className={icxstyles.logo}>
            <Image src="/icx_logo_white.svg" alt="icx-logo" width={160} height={30} />
          </div>
          <div>
            { headerLinks.map((link: HeaderLink) => {
              return <a key={`header-link-${link.label}}`} href={link.url}>{link.label}</a>
            })}
          </div>
        </div>

        {/* hero */}
        <div className={icxstyles['hero-bg']} />
        <div className={icxstyles.hero}>
          <div>
            <h1>Get your <span className={icxstyles.highlight}>Food Handler Certificate</span> online</h1>
            <h1 className={icxstyles.clickable}>
              <a 
                href="https://my.instacert.ca/urlcheckout/add?product=7&qty=1"
                className={icxstyles.highlight}
                target="_blank"
                rel="noreferrer">Register now</a></h1>
          </div>
          <Image src="/icc-value.png" alt="icc-value-graphic" width={350} height={311} layout="fixed" />
        </div>

        <div className={icxstyles.center}>
          <StepsSection />
          <PricingSection />
          <FAQSection faqs={faqs} />
          <CTASection />
          <Footer footer={footer} />
        </div>
      </main>
    </div>
  )
}

export default Home

export const getStaticProps = async () => {
  const stories = { stories: await getStoryblokStories() };
  const layout = jsonata("stories[slug='layout']").evaluate(stories);
  const home = jsonata("stories[name='Home']").evaluate(stories);
  return { props: {
    // stories, // debug
    layout,
    home,
  } };
};
