import type { NextPage, GetStaticProps, InferGetStaticPropsType } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import jsonata from 'jsonata';

import { getStoryblokStories, StoryblokLayoutHeaderLink as HeaderLink } from 'moncel-one-sdk/cdn';

import StepsSection from './landing/steps';

import 'bootstrap/dist/css/bootstrap.css'
import styles from '../styles/Home.module.css'
import icxstyles from '../styles/icx.module.css'

const Home = (props: InferGetStaticPropsType<typeof getStaticProps>) => {
  const headerLinks = props.layout.content.header[0].navigation;
  return (
    <div className={styles.container}>
      <Head>
        <title>Food Handler Certificate Course Online | 100% Online</title>
        <meta name="description" content="Generated by create next app" />
        {/* bootstrap responsive viewport meta tag */}
        {/* <meta name="viewport" content="width=device-width, initial-scale=1" />  */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={icxstyles.page}>
        
        {/* header */}
        <div className={icxstyles['header-bg']} />
        <div className={icxstyles.header}>
          <div className={icxstyles.logo}>
            <Image src="/icx_logo_white.svg" alt="icx-logo" width={160} height={30} />
          </div>
          <div>
            { headerLinks.map((link: HeaderLink) => {
              return <a key={`header-link-${link.label}}`} href={link.url}>{link.label}</a>
            })}
          </div>
          
        </div>

        {/* hero */}
        <div className={icxstyles['hero-bg']} />
        <div className={icxstyles.hero}>
          <div>
            <h1>Get your <span className={icxstyles.highlight}>Food Handler Certificate</span> online</h1>
            <h1>
              <a 
                href="https://my.instacert.ca/urlcheckout/add?product=7&qty=1"
                className={icxstyles.highlight}
                target="_blank"
                rel="noreferrer">Register now</a></h1>
          </div>
          <Image src="/icc-value.png" alt="icc-value-graphic" width={350} height={311} layout="fixed" />
        </div>
        
        <div className={icxstyles.center}>
          <StepsSection />
        </div>
      </main>
    </div>
  )
}

export default Home

export const getStaticProps = async () => {
  // The entire story json is available here on server side; the ui container can split/prune it for data that the ui depends on
  const stories = { stories: await getStoryblokStories() };
  const layout = jsonata("stories[slug='layout']").evaluate(stories);
  return { props: {
    stories,
    layout
  } };
};
